# Generated by Django 4.2.6 on 2023-11-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_activationlink'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivationLink',
            new_name='ActivationToken',
        ),
        migrations.RenameField(
            model_name='activationtoken',
            old_name='link',
            new_name='token',
        ),
    ]
