# Generated by Django 4.2.6 on 2023-11-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_hash_delete_activationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(max_length=64),
        ),
    ]
