# Generated by Django 4.2.6 on 2023-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_logincodes_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincodes',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
